
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lwz7254591
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai


  thymeleaf:
    cache: false

